/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author farid
 */
public class ExamResults extends javax.swing.JFrame {

    /**
     * Creates new form ExamResults
     */
    public ExamResults() {
        initComponents();
        Tools.setFrameAtMiddle(this);
        this.setTitle("Exam Results");
        this.setAlwaysOnTop(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Firstname", "Lastname", "Grade" }));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String command = "SELECT firstname, lastname, class, subject_name , score FROM score, student WHERE score.student_id = student.student_id";
        ResultSet rs = new DataAccessLayer().selectRecords(command);
        try{
        rs.last();
        int totalrows = rs.getRow();
        rs.beforeFirst();
        
        String columns[] = {"firstname","lastname","grade","subject","score"};
        Object[][] data = new Object[totalrows][columns.length];
        
        int y = 0;
        while(rs.next()){
            data[y][0] = rs.getString(1);
            data[y][1] = rs.getString(2);
            data[y][2] = rs.getString(3);
            data[y][3] = rs.getString(4);
            data[y][4] = rs.getString(5);
            y++;
        }
        
        jTable1 = new JTable(data,columns);
        jScrollPane1.setViewportView(jTable1);
        jTable1.setFont(new Font("Serif", Font.PLAIN, 20));
        jTable1.setRowHeight(40);
        
        }
        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "SQL Exception caught");
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Firstname")){
            String command = "SELECT firstname, lastname, class, subject_name , score FROM score, student WHERE score.student_id = student.student_id AND firstname LIKE '%" + jTextField1.getText() + "%'";
            ResultSet rs = new DataAccessLayer().selectRecords(command);
            try{
            rs.last();
            int totalrows = rs.getRow();
            rs.beforeFirst();

            String columns[] = {"firstname","lastname","grade","subject","score"};
            Object[][] data = new Object[totalrows][columns.length];

            int y = 0;
            while(rs.next()){
                data[y][0] = rs.getString(1);
                data[y][1] = rs.getString(2);
                data[y][2] = rs.getString(3);
                data[y][3] = rs.getString(4);
                data[y][4] = rs.getString(5);
                y++;
            }

            jTable1 = new JTable(data,columns);
            jScrollPane1.setViewportView(jTable1);
            jTable1.setFont(new Font("Serif", Font.PLAIN, 20));
            jTable1.setRowHeight(40);
            }
            catch(SQLException e){
                javax.swing.JOptionPane.showMessageDialog(this, "SQLException");
            }
        }
        else if(jComboBox1.getSelectedItem().equals("Lastname")){
            String command = "SELECT firstname, lastname, class, subject_name , score FROM score, student WHERE score.student_id = student.student_id AND lastname LIKE '%" + jTextField1.getText() + "%'";
            ResultSet rs = new DataAccessLayer().selectRecords(command);
            try{
            rs.last();
            int totalrows = rs.getRow();
            rs.beforeFirst();

            String columns[] = {"firstname","lastname","grade","subject","score"};
            Object[][] data = new Object[totalrows][columns.length];

            int y = 0;
            while(rs.next()){
                data[y][0] = rs.getString(1);
                data[y][1] = rs.getString(2);
                data[y][2] = rs.getString(3);
                data[y][3] = rs.getString(4);
                data[y][4] = rs.getString(5);
                y++;
            }

            jTable1 = new JTable(data,columns);
            jScrollPane1.setViewportView(jTable1);
            jTable1.setFont(new Font("Serif", Font.PLAIN, 20));
            jTable1.setRowHeight(40);
            }
            catch(SQLException e){
                javax.swing.JOptionPane.showMessageDialog(this, "SQLException");
            }
        }
        else if(jComboBox1.getSelectedItem().equals("Grade")){
            String command = "SELECT firstname, lastname, class, subject_name , score FROM score, student WHERE score.student_id = student.student_id AND class LIKE '%" + jTextField1.getText() + "%'";
            ResultSet rs = new DataAccessLayer().selectRecords(command);
            try{
            rs.last();
            int totalrows = rs.getRow();
            rs.beforeFirst();

            String columns[] = {"firstname","lastname","grade","subject","score"};
            Object[][] data = new Object[totalrows][columns.length];

            int y = 0;
            while(rs.next()){
                data[y][0] = rs.getString(1);
                data[y][1] = rs.getString(2);
                data[y][2] = rs.getString(3);
                data[y][3] = rs.getString(4);
                data[y][4] = rs.getString(5);
                y++;
            }

            jTable1 = new JTable(data,columns);
            jScrollPane1.setViewportView(jTable1);
            jTable1.setFont(new Font("Serif", Font.PLAIN, 20));
            jTable1.setRowHeight(40);
            }
            catch(SQLException e){
                javax.swing.JOptionPane.showMessageDialog(this, "SQLException");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamResults().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
